apiVersion: apps/v1
kind: Deployment
metadata:
  name: aws-devops-demo
  labels:
    app: aws-devops-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: aws-devops-demo
  template:
    metadata:
      labels:
        app: aws-devops-demo
    spec:
      containers:
        - name: aws-devops-demo
          image: aws-devops-demo:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 20